name: 'Publish to Sonatype'
description: 'Publish a scala package from a build.sbt'
inputs:
  gpg-private-key:
    description: GPG private key for signing the published artifacts
    required: true
  gpg-passphrase:
    description: Passphrase for the GPG key
    required: true
  nexus-username:
    description: Username (not email!) for your Nexus repository manager account
    required: true
  nexus-password:
    description: Password for your Nexus account
    required: true
  working-directory:
    description: "Path within the repo to the folder where the build.sbt file lives"
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: import GPG key
      run: |
        echo -e "${{ inputs.gpg-private-key }}" | gpg --batch --import --no-tty
        echo "hello world" > temp.txt
        gpg --detach-sig \
          --yes -v \
          --output=/dev/null \
          --pinentry-mode loopback \
          --passphrase "${{ inputs.gpg-passphrase }}" temp.txt
        rm temp.txt
      shell: bash
    - name: publish artefacts
      # TODO maybe specify version?
      run: |
        sbt "release cross with-defaults"
      shell: bash
      env:
        SONATYPE_USERNAME: ${{ inputs.nexus-username }}
        SONATYPE_PASSWORD: ${{ inputs.nexus-password }}
        PGP_PASSPHRASE: ${{ inputs.gpg-passphrase }}
      working-directory: ${{ inputs.working-directory }}

branding:
  icon: package
  color: green
