name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - renovate/**

permissions: {}

jobs:
  test-publish-mvn:
    name: It publishes sbt artefacts
    runs-on: ubuntu-latest
    environment: Publish to Nexus
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5.3.0
        with:
          java-version: '17'
          distribution: 'adopt'
      - uses: sbt/setup-sbt@3afe9cf056c5d139bfc46579af1192d77a2f0821 # v1.4.0
      - name: Set unique package version
        id: set-version
        run: |
          version=0.0.$GITHUB_RUN_NUMBER
          echo "ThisBuild / version := \"$version\"" > version.sbt
          echo "version=$version" >> $GITHUB_OUTPUT
        working-directory: "test"
      - name: Test the action
        uses: ./
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
          nexus-username: ${{ secrets.SONATYPE_USERNAME }}
          nexus-password: ${{ secrets.SONATYPE_PASSWORD }}
          working-directory: "test"
